### ISSUE TITLE
Issue showing skeleton with kinect-wrapper

### ISSUE THREAD

**Issue by urielmtz** [robotology/kinect-wrapper#7]
Hello,

We are having an issue with the kinect-wrapper. Basically, we are running `kinectServer` and `kinectClientExample`, in which the player, depth and rgb images are correctly displayed. However, the skeleton isn't sending any data. The `kinect-wrapper` is up-to-date, so we don't know what the problem would be. 

I am wondering if do you have any idea about how to solve this issue?

Cheers
Uriel

**Comment by pattacini** [comment]
@Tobias-Fischer do you have any chance to help on this? I know people in London are currently using `kinect-wrapper` much more often than us :smile:

**Comment by Tobias-Fischer** [comment]
Sure. I'll have a look on Monday.

**Comment by pattacini** [comment]
Thanks a lot!

**Comment by Tobias-Fischer** [comment]
Hi @urielmtz, 
Are you using the Kinect SDK or the OpenNI driver? To me it sounds like you don't go in the initial pose (see https://mutatedfantasy.files.wordpress.com/2011/04/drawing1.jpg?w=698&h=350 ). Even though the player is shown, you have to go in this pose do the skeleton tracking starts. 
Please give it a try and let me know whether it works.

Best, Tobias

**Comment by lukeboorman** [comment]
Thanks, will give it another try, we did the normal poses and we have a non-yarp version which works for controlling a robot arm.

We are running on kinect-SDK V1.8 as we are running using the windows machine for the microsoft SAPI, could that be the issue

Thanks

**Comment by Tobias-Fischer** [comment]
Hey @lukeboorman, 
What do you mean by non-yarp version? And what are normal poses (did you do the initial pose)?

As always, I'm not the right person to ask about any Windows issues .. As far as I know, at Imperial we always use(d) the OpenNI version.

Best, Tobias

**Comment by lukeboorman** [comment]
@Tobias-Fischer 
I think the other version we have uses C++ but is running on a linux laptop so will be using openNI!

I will try the kinect-wrapper on one of our iCub Linux machines with openNI

**Comment by pattacini** [comment]
Closing.
Feel free to reopen it.
